### ISSUE TITLE
[BUG] Mismatched protocol between frontend and backend causes shortlinks to fail

### ISSUE THREAD

**Issue by lichray** [compiler-explorer/compiler-explorer#2309]
**Describe the bug**

When pressing the share button from a custom domain, the shorten URL panel is always loading.  But the backend (terminal where runs compiler-explorer) prints the right subhash, and you can use https://my-custom-domain/z/SUBHASH to access.

**To Reproduce**

Press the button on https://godbolt.miator.net

**Expected behavior**

It should return me a shorten URL out of my domain.

**Link**

https://godbolt.miator.net

**Screenshots**

![image](https://user-images.githubusercontent.com/433009/97835720-6e8cd300-1ca0-11eb-86fa-31ab9cd01f42.png)

**Desktop**

 - OS: Microsoft Windows [Version 10.0.18363.1139]
 - Browser: Edge
 - Version: 86.0.622.51

**Additional context**

I've created `etc/config/compiler-explorer.local.properties`  with

```ini
allowedShortUrlHostRe=^godbolt.miator.net$
remoteStorageServer=https://godbolt.miator.net
privacyPolicyEnabled=true
```

Nothing works.

**Comment by apmorton** [comment]
javascript console shows the following error:

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://godbolt.miator.net/z/onMeej' cannot be created in a document with origin 'https://godbolt.miator.net' and URL 'https://godbolt.miator.net/'.
```

and the network shows the following response to the shortener request:
```
{"url":"http://godbolt.miator.net/z/onMeej"}
```

Your backend thinks the site is http, but its running https on the frontend, as a result the backend is returning shortlinks with the incorrect protocol and our code blows up trying to push history in the browser.

The solution is to add an `X-Forwarded-Proto` header to whatever reverse proxy you have sitting in front of CE that is terminating TLS.

See #1588

**Comment by lichray** [comment]
Solved in Nginx.
Can we add some helpful messages to the frontend to give users some clue about this situation?

**Comment by apmorton** [comment]
will leave this open to track the issue

**Comment by ipatix** [comment]
I'm having a problem where shortlinks won't work either, but I get the following error:
```
Uncaught DOMException: The operation is insecure.
```
Is that related? If or if not, how do I fix it?

**Comment by RubenRBS** [comment]
Could you tell us what are your OS & Browser versions?

**Comment by ipatix** [comment]
Firefox 89.0.2 64 Bit, Windows 10 Pro 2004

EDIT: I just tried it with Chromium 90.0.4430.93 on my Linux machine and I get the exact same DOMException as apmorton.
I also tried adding `proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;` to the nginx config for that instance, but that apparently does not fix it.

**Comment by partouf** [comment]
> Firefox 89.0.2 64 Bit, Windows 10 Pro 2004
> 
> EDIT: I just tried it with Chromium 90.0.4430.93 on my Linux machine and I get the exact same DOMException as apmorton.
> I also tried adding `proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;` to the nginx config for that instance, but that apparently does not fix it (this was mostly a "how to I set X-Forwarded-Proto with nginx" google attempt and I honestly don't quite understand what it really does and why it'd be needed).
> 
> EDIT2: This is my current nginx configuration:
> 
> ```
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     server_name *censored*;
> 
>     # fixes short links ???
>     proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
> 
>     include locations/acme-challenge.conf;
> 
>     auth_basic "Compiler Explorer Login";
>     auth_basic_user_file "*censored*";
> 
>     index index.html;
> 
>     location / {
>         proxy_pass http://localhost:10240;
>         proxy_set_header Host $host;
>         proxy_buffer_size 128k;
>         proxy_buffers 4 256k;
>         proxy_busy_buffers_size 256k;
>     }
> }
> ```

Just to be sure, did you restart your nginx?

**Comment by ipatix** [comment]
Yes!

**Comment by partouf** [comment]
I think technically you should put it in the part where you do the proxy_pass, but not sure that will matter in practice.

**Comment by ipatix** [comment]
Just tested it, still doesn't work.

**Comment by partouf** [comment]
Can you look at your network traffic in chrome/ff developertools and see what request headers + response you get from the `shortener` API call when you click to share?

**Comment by ipatix** [comment]
Response Headers:
```
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-origin: *
cache-control: public, max-age=600
content-length: 36
content-type: application/json; charset=utf-8
date: Sun, 04 Jul 2021 11:46:09 GMT
etag: W/"24-g3RpXrcnMJT08mWASO1SX0la5r4"
server: nginx
vary: Accept-Encoding
x-powered-by: Express
```
Request Headers:
```
:authority: xxxxxxxxx
:method: POST
:path: /api/shortener
:scheme: https
accept: application/json, text/javascript, */*; q=0.01
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Basic cHJldDptZXRyb3N1eDY0NQ==
content-length: 2148
content-type: application/json
origin: https://xxxxxxxxx
referer: https://xxxxxxxxx/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
x-requested-with: XMLHttpRequest
```
Response (manually typing in this URL does work):
```
{"url":"http://xxxxxxxx/z/WsGYqr"}
```

**Comment by partouf** [comment]
(perhaps unrelated, but slightly confused, how would a http url when you have nginx sitting in front serving https?)

Which revision of the CE do you have, a recent one?

Fyi, so the reason you need to forward the protocol, is because CE uses `req.protocol` here https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/storage/base.js#L120 - and the official protocol is ofcourse HTTP. The Forward fills in an extra header that says it's actually HTTPS and should use that instead.

So it definitely has to be something not right about your nginx setup, but not sure what. Maybe an extra config file that conflicts, or if you're using a docker with nginx maybe you need a rebuild?

If all fails, you could just change the line used in the code that I linked and change `${req.protocol}` to `https`

**Comment by ipatix** [comment]
Ohhh, so after a bit of guessing and more accurate googling I tried the following:
```
proxy_set_header X-Forwarded-Proto $scheme;
```
This solved my problem and short links work now!

**Comment by partouf** [comment]
> Ohhh, so after a bit of guessing and more accurate googling I tried the following:
> 
> ```
> proxy_set_header X-Forwarded-Proto $scheme;
> ```
> 
> This solved my problem and short links work now!

Oh, of course. Totally missed that you didn't have that. Glad you found it!

**Comment by ipatix** [comment]
Yeah, I previously tried `proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;` which didn't do the right job.

**Comment by partouf** [comment]
I usually have these two in my configs:
```
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
```
And I got the two mixed up and thought you had it correct.
