### ISSUE TITLE
gcc cobol nightly failing on install step

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#6725]
```
26204   │ 2024-07-26T00:42:57.9500640Z mkdir -p -- /opt/compiler-explorer/gcc-build/staging/share/man/man7
26205   │ 2024-07-26T00:42:57.9514211Z /bin/bash ../../gcc-cobol-master-20240726/gcc/../install-sh -c -s -v gcobol                \
26206   │ 2024-07-26T00:42:57.9515011Z    /opt/compiler-explorer/gcc-build/staging/bin/gcobol
26207   │ 2024-07-26T00:42:57.9541546Z ../../gcc-cobol-master-20240726/gcc/../install-sh: invalid option: -v
26208   │ 2024-07-26T00:42:57.9542840Z make[2]: *** [../../gcc-cobol-master-20240726/gcc/cobol/Make-lang.in:177: cobol.install-common] Error 1
26209   │ 2024-07-26T00:42:57.9543865Z make[2]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir/gcc'
26210   │ 2024-07-26T00:42:57.9568030Z make[1]: *** [Makefile:4832: install-strip-gcc] Error 2
26211   │ 2024-07-26T00:42:57.9568824Z make[1]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir'
26212   │ 2024-07-26T00:42:57.9569528Z make: *** [Makefile:2855: install-strip] Error 2
26213   │ 2024-07-26T00:43:01.9194952Z ##[error]Process completed with exit code 2.
26214   │ 2024-07-26T00:43:01.9247933Z ##[group]Run ./post-run.sh "gcc_cobol_master" "" "" "1721953880"
```
Probably an upstream bug.

**Comment by dkm** [comment]
Upstream has been notified and should fix the install command. Will keep an eye :)

**Comment by dkm** [comment]
This is still failing. I'll need to try a bit harder and see myself.

**Comment by dkm** [comment]
https://github.com/compiler-explorer/compiler-workflows/actions/workflows/build-daily-gcc_cobol_master.yml

**Comment by thesamesam** [comment]
The issue is still at https://gitlab.cobolworx.com/COBOLworx/gcc-cobol/-/blob/master+cobol/gcc/cobol/Make-lang.in#L177. They should just drop the `-v` for now. At a bunch of places in GCC, we do:
```
AC_PROG_INSTALL
test -z "$INSTALL_PROGRAM" && INSTALL_PROGRAM='${INSTALL}'
AC_SUBST(INSTALL_PROGRAM)
```
but I've not checked if/why that doesn't take effect for cobol/.

**Comment by dkm** [comment]
> The issue is still at https://gitlab.cobolworx.com/COBOLworx/gcc-cobol/-/blob/master+cobol/gcc/cobol/Make-lang.in#L177. They should just drop the `-v` for now. At a bunch of places in GCC, we do:
> 
> ```
> AC_PROG_INSTALL
> test -z "$INSTALL_PROGRAM" && INSTALL_PROGRAM='${INSTALL}'
> AC_SUBST(INSTALL_PROGRAM)
> ```
> 
> but I've not checked if/why that doesn't take effect for cobol/. We only seem to do that for target libraries or build tools, not FEs.
> 
> No uses in GCC do `-v`.

Yes, I think that was the conclusion from some mail exchanges with James from early sept... 
/me checks notes....
Yes, James' conclusion was:

> I probably added -v so that install would report the installed name. I’ll remove it. 

Thanks for looking into this @thesamesam !

**Comment by dkm** [comment]
Now failing because of missing object file:
```
18313   │ 2025-01-20T00:36:30.0898780Z /usr/bin/ld: cannot find cobol/valconv-copy.o: No such file or directory
```

**Comment by jklowden** [comment]
> No uses in GCC do `-v`.

I just removed `-v` for install in Make-lang.in for _parser_ branch.  It should find its way to master+cobol today or tomorrow.  

In my local build directory I have `gcc/cobol/valconv-copy.o`.  Not sure how to interpret the issue.

**Comment by dkm** [comment]
Thanks @jklowden ! We've disabled the nightly because I didn't take the time to try and fix this small issue. We can re-enable it and see if the valconv error is gone. Maybe there's a race in the makefile?

**Comment by rdubner** [comment]
I am Bob Dubner, Jim's partner in COBOL crime.  I just pushed into master+cobol the version that removes the `-v` switch.

There are two source files in the libgcobol/ directory that are part of the build both for the libgcobol.so library, and for the cobol1 executable.  Those files are `valconv.cc` and `charmaps.cc`.  Rather than have two copies of each, the Makefile makes copies of them, renamed with `-copy` inserted to forestall massive confusion, in the gcc/cobol/ directory.  Of course, I _tried_ to set up the dependency chains properly.

The build process clearly works on my machines, Jim's machines, and on our pipeline machines ("...but we have a light bulb just like yours, and it's working fine...").  I'll stare at the Makefile and see if anything jumps out.

**Comment by partouf** [comment]
> The build process clearly works on my machines, Jim's machines, and on our pipeline machines ("...but we have a light bulb just like yours, and it's working fine..."). I'll stare at the Makefile and see if anything jumps out.

From what I've seen from the pipeline log on gitlab at least, I didn't see valconv-copy.o being built, it was just linked against, so it's probably being re-used from when it did build that object file and it remained there without being cleaned up. But I don't know how it's all set up.

**Comment by partouf** [comment]
I have done some experimenting. At some point I saw `charmaps-copy.o` being compiled, but not `valconv-copy.o` - and as they were being described in the .in files the same way, I wondered if there's a configure-make step going wrong or that maybe it was parallelized in the wrong way and ending up to be compiled later.

Logging 1: https://github.com/compiler-explorer/infra/actions/runs/12955359568/job/36139312340#step:6:17637

I messed with some packages and then I tried a plain `make` without `-j...`, but after 39minutes of building it has come to the conclusion `valconv-copy.o` was not built, however, `charmaps-copy.o` was not built this time either. And it may be that my earlier messing about with some installed packages messed that up.

My messing about was that I added `apt install`:
* pkg-config
* autoconf

I added autoconf because I saw the following in our configure logging:
```
  checking for aclocal... ${SHELL} /opt/compiler-explorer/gcc-build/binutils-2.42/missing aclocal-1.15
  checking for autoconf... ${SHELL} /opt/compiler-explorer/gcc-build/binutils-2.42/missing autoconf
  checking for autoheader... ${SHELL} /opt/compiler-explorer/gcc-build/binutils-2.42/missing autoheader
```

However this remained unchanged after installing autoconf.

I deleted the extra installs, and... neither is being built now.

Logging 2: https://github.com/compiler-explorer/infra/actions/runs/12956776008/job/36143796841#step:6:18063

So now I don't know what the difference was between Logging 1 and 2, but it's a little mindboggling either way.

**Comment by rdubner** [comment]
Okay.

 

I just pushed a brand-new version of master+cobol.

 

It includes some modifications to Make-lang.in, which I think might help improve things.

 

First off, the copies of valconv.cc and charmaps.cc are now being given the names valconv-dupe.cc and charmaps-dupe.cc.  I feel those names are more accurate, and less likely to cause confusion with cdf-copy.cc, which is a genuine primary source file.  (COBOL has an important feature named COPY, hence the naming.)

 

It turned out that valconv-copy.cc was part of the repository, when it should not have been.

 

And there were some all-but-contradictory things about the dependencies for what were the -copy (now -dupe) files.  That’s more orderly now than it was.

 

And all we can do is see what happens.  The gcc/cobol/Make-lang.in and resulting Makefile in the build tree apparently make heavy use of default implicit rules, which always makes me nuts because of cases like this, where something weird is going on and I can’t put debugging echo statements in so as to see what’s going on.

 

That said, I hope you can give this latest master+cobol a shot.  And if still does weird things, I’ll want to join you in looking at the detailed log files.  It is a bit astonishing that my machine and our pipeline CI/CD machine never have a problem, while your environmnet always does.

 

Come to think of it, what *is* your environment?  I am running Ubuntu 22.04 and 24.04.  If you are doing something significantly different, then maybe I can spin up a virtual machine like yours and actually try find the problem when it is out in the middle of the living room and not hiding under the couch.

**Comment by partouf** [comment]
Both -dupe files are being built correctly now.

Build phase also seems to have succeeded, but it fails on the `make install` bit.

https://github.com/compiler-explorer/infra/actions/runs/12958790288/job/36149857661#step:6:25472

unsure at what its trying to do here

**Comment by mattgodbolt** [comment]
To make life easier the end of the log partouf refers to is:
```
2025-01-24T22:51:31.0007278Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs po
2025-01-24T22:51:31.0039892Z : --statistics -o po/zh_TW.gmo ../../gcc-cobol-master-20250124/gcc/po/zh_TW.po
2025-01-24T22:51:31.6082980Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/lib/gcc/x86_64-linux-gnu/15.0.1
2025-01-24T22:51:31.6116114Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/libexec/gcc/x86_64-linux-gnu/15.0.1
2025-01-24T22:51:31.6149406Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/bin
2025-01-24T22:51:31.6181286Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/include
2025-01-24T22:51:31.6212107Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/share/info
2025-01-24T22:51:31.6242397Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/share/man/man1
2025-01-24T22:51:31.6278905Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/share/man/man3
2025-01-24T22:51:31.6326173Z mkdir -p -- /opt/compiler-explorer/gcc-build/staging/share/man/man3
2025-01-24T22:51:31.6342705Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/share/man/man7
2025-01-24T22:51:31.6389947Z mkdir -p -- /opt/compiler-explorer/gcc-build/staging/share/man/man7
2025-01-24T22:51:31.6403901Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../mkinstalldirs /opt/compiler-explorer/gcc-build/staging/share/cobol/udf
2025-01-24T22:51:31.6453599Z mkdir -p -- /opt/compiler-explorer/gcc-build/staging/share/cobol/udf
2025-01-24T22:51:31.6468611Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../install-sh -c -s gcobol				\
2025-01-24T22:51:31.6469777Z 	/opt/compiler-explorer/gcc-build/staging/bin/gcobol
2025-01-24T22:51:31.6878671Z /bin/bash ../../gcc-cobol-master-20250124/gcc/../install-sh -c -s ../../gcc-cobol-master-20250124/gcc/cobol/gcobc /opt/compiler-explorer/gcc-build/staging/bin/
2025-01-24T22:51:31.6966906Z x86_64-linux-gnu-strip: /opt/compiler-explorer/gcc-build/staging/bin//_inst.199741_: file format not recognized
2025-01-24T22:51:31.6985479Z make[2]: *** [../../gcc-cobol-master-20250124/gcc/cobol/Make-lang.in:268: cobol.install-common] Error 1
2025-01-24T22:51:31.6987059Z make[2]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir/gcc'
2025-01-24T22:51:31.7025934Z make[1]: *** [Makefile:4832: install-strip-gcc] Error 2
2025-01-24T22:51:31.7027520Z make[1]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir'
2025-01-24T22:51:31.7034277Z make: *** [Makefile:2855: install-strip] Error 2
2025-01-24T22:51:38.4977653Z ##[error]Process completed with exit code 2.
2025-01-24T22:51:38.5068088Z Post job cleanup.
2025-01-24T22:51:38.5964855Z [command]/usr/bin/git version
2025-01-24T22:51:38.6002222Z git version 2.34.1
```

**Comment by rdubner** [comment]
I can’t make heads or tails of the error, either, although I am pleased my changes to Make-lang.in seems to have moved things forward.I am not familiar with this aspect of github. Where can I find the build.sh file?On Jan 24, 2025, at 17:57, Patrick Quist ***@***.***> wrote:﻿
Both -dupe files are being built correctly now, so thanks!
Build phase also seems to have succeeded, but it fails on the make install bit.
https://github.com/compiler-explorer/infra/actions/runs/12958790288/job/36149857661#step:6:25472
unsure at what its trying to do here

**Comment by partouf** [comment]
You can find our builder here: https://github.com/compiler-explorer/gcc-builder

It's a docker container, so you can build the dockerfile and run it yourself.

The build script is here https://github.com/compiler-explorer/gcc-builder/blob/main/build/build.sh

For cobol we run it with `cobol-master` and it will fall into this if https://github.com/compiler-explorer/gcc-builder/blob/main/build/build.sh#L104

Here's it's configured and installed
https://github.com/compiler-explorer/gcc-builder/blob/main/build/build.sh#L315

**Comment by rdubner** [comment]
Thank you very much. 

<grin> So far I have been successful in my efforts to *not* learn anything about Docker. 

I guess that’s coming to an end.

**Comment by rdubner** [comment]
I am pleased to report that I have been able to reproduce the error on my workhorse development computer.

 

Tomorrow we shall see what we shall see.

**Comment by rdubner** [comment]
I have pushed a version of master+cobol that the Docker package builds successfully on my local machine.

 

A few months back, we added the shell script “gcobc”, which attempts to invoke gcobol using command-line options used by GnuCOBOL.  

 

The installation recipe for gcobc had it flagged as a program, so the install process was attempting to strip it.  strip(1) fails on text files.

 

I have it flagged now as just an ordinary file, and the build.sh runs to completion.

**Comment by rdubner** [comment]
@dkm, perhaps I was unclear. I believe that if the cobol-master build is re-enabled, that it will run successfully. 

Can that be tested?

**Comment by dkm** [comment]
/me arrives after everything has been discussed and fixed 😅 
Sure, we can re-enable it and see if it works better now! Will take care of this today

**Comment by dkm** [comment]
Done!

**Comment by dkm** [comment]
And it's green again 🎉 So next nightly build should be OK. Thanks all for fixing this :)

**Comment by rdubner** [comment]
And thank you all.  I grew up in a world where the proprietary nature of software was simply assumed.  I spent a bunch of time in the world of broadcast television and various mission-critical systems (think blood chemistry analysis and city-wide burglar alarm central control) back in a time when a reboot had to finish in at most two or three seconds, not minutes, and so the use of almost any "operating system" was precluded.  We didn't think in terms of "up time"; that implied some "down time" was tolerable, which it wasn't.  (Down time was endured, usually with somebody yelling at you -- not tolerated.) We did everything ourselves; I/O, file systems, communications...everything.)  

So, I am a relative latecomer to the world of FOSS and cooperative volunteer efforts, and I don't automatically think in those terms.  It's a recurring delight to see how well this model actually can work!

**Comment by dkm** [comment]
and btw, I'll see @jklowden at FOSDEM this weekend 👍

**Comment by dkm** [comment]
```
25808   │ 2025-02-01T00:29:42.7026434Z mkdir -p /opt/compiler-explorer/gcc-build/staging/bin/udf/
25809   │ 2025-02-01T00:29:42.7054028Z /usr/bin/install -c -m 644 ../../gcc-cobol-master-20250201/gcc/cobol/udf/*  /opt/compiler-explorer/gcc-build/staging/share/cobol/udf
25810   │ 2025-02-01T00:29:42.7079777Z /usr/bin/install: cannot create regular file '/opt/compiler-explorer/gcc-build/staging/share/cobol/udf': No such file or directory
25811   │ 2025-02-01T00:29:42.7080758Z make[2]: *** [../../gcc-cobol-master-20250201/gcc/cobol/Make-lang.in:270: cobol.install-common] Error 1
25812   │ 2025-02-01T00:29:42.7081434Z make[2]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir/gcc'
25813   │ 2025-02-01T00:29:42.7103091Z make[1]: *** [Makefile:4832: install-strip-gcc] Error 2
25814   │ 2025-02-01T00:29:42.7103770Z make[1]: Leaving directory '/opt/compiler-explorer/gcc-build/objdir'
25815   │ 2025-02-01T00:29:42.7105736Z make: *** [Makefile:2855: install-strip] Error 2
25816   │ 2025-02-01T00:29:47.2158122Z ##[error]Process completed with exit code 2.
25817   │ 2025-02-01T00:29:47.2206439Z ##[group]Run ./post-run.sh "gcc_cobol_master" "" "" "1738369043"
```
https://github.com/compiler-explorer/compiler-workflows/actions/runs/13082939249/job/36509917948
Something broken around this `udf` subdir...

**Comment by dkm** [comment]
Fixed for some time now!
